### ISSUE TITLE
append is not a member of the String class

### ISSUE THREAD

**Issue by AcuarioCat** [PaulStoffregen/EEPROM#14]
Compilation fails (Arduino Nano) as append is not a member of the String class.
Used in EEPROMClass::get function

**Comment by PaulStoffregen** [comment]
This EEPROM library is meant for Teensy.

Do not use it with Arduino Nano.

If you are using the default EEPROM library that comes with Arduino, that is NOT this code.  Ask for help on the Arduino Forum.  If the problem is a defect in Arduino's EEPROM library, people on Arduino Forum will direct you to the proper place to create an issue.

This is absolutely the wrong place for anything involving Arduino Nano.  Use the Arduino Forum.
